GET http://127.0.0.1:8000/

###
GET http://127.0.0.1:8000/games

###
GET http://127.0.0.1:8000/games/12

###
POST http://127.0.0.1:8000/games
Content-Type: application/json; 

{
"name": "GTA Vicity",
"price": 23.99,
"releaseDate": "2003-04-17"
}

###
PUT http://127.0.0.1:8000/games/12
Content-Type: application/json; 

{
"name": "GTA Vicity",
"price": 24.99,
"releaseDate": "2003-04-17"
}

###
DELETE  http://127.0.0.1:8000/games/12